### PR TITLE
Use worker socket -> polymer1/2

### PR DESCRIPTION
**Pull request by chapulina**
https://github.com/osrf/polymer-ros-websocket/pull/3 targetting the correct branch

### CODE REVIEW

**Review by jubeira — APPROVED** [review]
LGTM.
For the record, I used my fork of `polymer-ros-rviz` at [this commit](https://github.com/jubeira/polymer-ros-rviz/commit/7a7439c0bd22153dac76f6b13a17451aafa3ec9d) to use both this change and the changes in `roslibjs` (the fork points at [this commit](https://github.com/jubeira/ros-websocket/commit/6278acf9d18d7ee503cae90c78a43801a8a8eef8) of `polymer-ros-websocket`).

I tested `pointcloud2`, `robot model`, `image`, `interactive markers` and `depth cloud` all at once and for a while; the memory usage didn't vary too much and I didn't see the client get stuck.

Screenshot from 2019-03-11 11-39-18

**Comment by jubeira** [comment]
@chapulina two small details:
- We should hold on merging this until the changes in `roslibjs` kick in right?
- Shall we make a new tag for this patch?

**Comment by chapulina** [comment]
>  We should hold on merging this until the changes in roslibjs kick in right?

+1

> Shall we make a new tag for this patch?

+1

**Comment by jubeira** [comment]
@chapulina https://github.com/RobotWebTools/roslibjs/pull/317 was merged; I can bump the version, merge and make the tag if you want; I'll stay tuned!

**Comment by chapulina** [comment]
Thanks for keeping an eye on it, @jubeira ! Feel free to make a release here once the upstream changes have been released.

**Pull request merged**
