### PR TITLE
V3 rollback and use new roslib

### PR DESCRIPTION
**Pull request by mvollrath**
Fixes Polymer 1 support and roslib version.

### CODE REVIEW

**Comment by mvollrath** [comment]
I need to fix this, something about the rollback commit didn't jive.

**Comment by mvollrath** [comment]
That's better.

**Review by jubeira — COMMENTED** [review]
Alright, so just to recap (please correct me if I'm wrong): we are updating `ros-rviz` to depend on `ros3djs#1.0.0`(to be released), which in turn depends on `roslib#1.0.0`; therefore we need `ros-rviz`'s dependencies to upgrade the dependency on `roslib` as well.

The dependency chain will end up being something like this:
```
ros-rviz --> ros3djs#1.0.0 --> roslib#1.0.0
ros-rviz --> ros-websocket#3.x --> roslib#1.0.0
ros-rviz --> ros-service#2.x --> ros-websocket#3.x --> roslib#1.0.0
```
So the rollback here is because we need to update `roslib` but at version `3.x` because of Polymer's required version right? If that's the case perhaps I'd make a branch from the latest `3.x` patch, update `roslib` and make a new tag instead of rolling back to previous code on the master branch. Then, `ros-service` and `ros-rviz` should depend on the new tag.
Does that make sense?

**Comment by mvollrath** [comment]
Sounds good, that's what I'd do if I had write access :+1:

**Comment by jubeira** [comment]
> Sounds good, that's what I'd do if I had write access +1

Maybe @chapulina can make the magic happen :grimacing:

**Comment by chapulina** [comment]
Created branch `polymer1/2` for the lack of a better name. Feel free to make a new PR targeting that branch, and it may be worth it adding a couple lines to the README explaining how the branches are related to the tagged versions.

**Pull request closed without merging**
