### PR TITLE
Use roslib 1.x

### PR DESCRIPTION
**Pull request by mvollrath**

### CODE REVIEW

**Review by jubeira — COMMENTED** [review]
Looks good!
Shall we bump the version in this branch as well?

**Comment by mvollrath** [comment]
Are you asking me to bump the version in this branch?  Otherwise I'll make a separate branch/PR for release.

**Comment by jubeira** [comment]
If I'm not mistaken this should be _the_ branch for new features or patches using Polymer 1-2. Our fork of `ros-rviz` should target releases 3.x, and the latest 'x' will be in this branch (master is already at 4.x using Polymer 3, so we won't be using it for now).

@chapulina please correct me if I'm wrong.

**Comment by mvollrath** [comment]
`osrf:polymer1/2` is the branch for Polymer 1-2, `EndPointCorp:use_roslib_1.x` (*this branch the PR is associated with*) is for setting the version of roslibjs in bower.json.  So yes, we should bump the version and do release things in `osrf:polymer1/2`

**Comment by mvollrath** [comment]
Now I see how doing it all in this PR makes it easier to test.

**Review by jubeira — APPROVED** [review]

**Pull request merged**
